project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Merna Saad"
  navbar:
    left:
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
      - href: fun.qmd
        text: Fun

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    mainfont: Inter
    include-in-header:
      - text: |
          <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600&family=Playfair+Display:wght@400;500;600;700&display=swap" rel="stylesheet">
